### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by susanxiong** [dchess/mothra#4]
On [More Account Models](https://github.com/dchess/mothra/wiki/More-Account-Models) page, under Org Type section:
`docker-compose exec web python manage.py makeigrations`
should be
`docker-compose exec web python manage.py makemigrations`

**Comment by susanxiong** [comment]
Same thing under the Organization section :)

**Comment by dchess** [comment]
Solved by https://github.com/dchess/mothra/wiki/More-Account-Models/48cfc45cd974b0cb70bb7b067cf1aa171339b8ba
